# Reference:
# https://github.com/codota/TabNine/blob/master/TabNine.toml

[language.rust]
command = "rls"
install = [
  ["rustup", "update"],
  ["rustup", "component", "add", "rls-preview", "rust-analysis", "rust-src"],
]

[language.javascript]
command = "flow"
args = ["lsp"]
install = [["npm", "install", "-g", "flow-bin"]]

[language.html]
command = "html-languageserver"
args = ["--stdio"]
install = [["npm", "install", "-g", "vscode-html-languageserver-bin"]]

[language.ocaml]
command = "ocaml-language-server"
args = ["--stdio"]
install = [["npm", "install", "-g", "ocaml-language-server"]]

[language.python]
command = "pyls"
install = [["pipx", "install", "python-language-server"]]

[language.c]
command = "clangd"
args = []

[language.cpp]
command = "clangd"
args = []

# [language.cpp]
# command = "cquery"
# args = ["--init={\"cacheDirectory\": \"${project_root}/.cquery_cache\"}"]

[language.haskell]
command = "hie"
args = ["--lsp"]

[language.go]
command = "gopls"
args = ["serve"]
install = [["go", "get", "-u", "golang.org/x/tools/gopls"]]

[language.bash]
command = "bash-language-server"
args = ["start"]

[language.dart]
# command = "dart_language_server"
command = "/home/tomasz/.pub-cache/bin/dart_language_server"
install = [["flutter", "pub", "global", "activate", "dart_language_server"]]
